### ISSUE TITLE
Passing params gives undefined

### ISSUE THREAD

**Issue by aizulhussin** [GeekyAnts/native-base-react-navigation-stack-navigator#1]
Hi,
i tried passing a parameter in LucyChat.js

```
<Button
            rounded
            danger
            style={{ marginTop: 20, alignSelf: "center" }}
            onPress={() => navigate("Profile",{id:'Lucy'})}
          >
```

However when i print the log in Profile.js, it gives undefined error

`console.log("ID:",this.props.navigation.state.params.id);`

**Comment by Jasbir23** [comment]
@aizulhussin , Nesting Navigator components is indeed creating problems with passing params.
Found some issues in [React Navigation](https://github.com/react-community/react-navigation/issues) related to this problem. Some of these include [#80](https://github.com/react-community/react-navigation/issues/80), [#1251](https://github.com/react-community/react-navigation/issues/1251), [#1237](https://github.com/react-community/react-navigation/issues/1237)
I tried to find a workaround this. Navigating something like this helps us pass params successfully.
```
const navigationAction = NavigationActions.navigate({
                routeName: "ProfileScreen", // <==== this is parent Profile tabNavigator
                action: NavigationActions.navigate({
                  routeName: "Profile", // <===== this is default child Screen for Profile tabNavigator
                  params: { name: "JADE" }
                })
              });
this.props.navigation.dispatch(navigationAction);
```
However this appends two components for the same Profile screen on the navigation stack.
Please add any other input that might help solve this.
Thanks
