### ISSUE TITLE
Image urls in Sidebar.js are dead and return 404

### ISSUE THREAD

**Issue by samifreesoul** [GeekyAnts/native-base-react-navigation-stack-navigator#6]

**Comment by mealbarracin10** [comment]
it seems that repository were removed, but this images was found in this repository https://github.com/GeekyAnts/NativeBase-KitchenSink,  for solution error 404 of images replace  
https://github.com/GeekyAnts/NativeBase-KitchenSink/raw/react-navigation/img/drawer-cover.png for it https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/assets/drawer-cover.png?raw=true and https://github.com/GeekyAnts/NativeBase-KitchenSink/raw/react-navigation/img/logo.png for it https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/assets/logo.png?raw=true and it will working

**Comment by Jasbir23** [comment]
Rectified in latest commits
